import type { QuizApiSourceKey } from "./sourceMap";

export type FallbackStrategy =
  | "none"
  | "translate_general_source"
  | "hybrid_api_plus_local_templates"
  | "curated_local_bank"
  | "future_custom_source_required";

export type QuizSubcategoryCard = {
  id: string;
  title: string;
  description: string;
  imageKey?: string;
  iconKey?: string;
  flagCode?: string | null;
  infoTitle: string;
  infoBody: string;
  apiSource: QuizApiSourceKey;
  apiCategory?: string | null;
  apiSubcategory?: string | null;
  fallbackStrategy: FallbackStrategy;
  fallbackRequired: boolean;
};

export type QuizCategorySection = {
  id: string;
  title: string;
  description: string;
  cardTitleColor: "orange";
  layout: "tile-grid";
  subcategories: QuizSubcategoryCard[];
};

const createCard = (card: QuizSubcategoryCard): QuizSubcategoryCard => card;
const createSection = (section: QuizCategorySection): QuizCategorySection => section;

export const categoryCatalog: QuizCategorySection[] = [
  createSection({
    id: "thinking",
    title: "تفكير",
    description: "فروع تعتمد على الملاحظة، المنطق، الصور، الألغاز، وربط الأدلة.",
    cardTitleColor: "orange",
    layout: "tile-grid",
    subcategories: [
      createCard({
        id: "thinking-within-image",
        title: "ضمن الصورة",
        description: "اكتشاف الشيء أو الفكرة من تفاصيل داخل صورة واحدة.",
        imageKey: "thinking-within-image",
        iconKey: "image-search",
        infoTitle: "ضمن الصورة",
        infoBody: "يعتمد هذا الفرع على أسئلة بصرية: صورة أو لقطة ويُطلب استخراج العنصر أو الفكرة الصحيحة منها.",
        apiSource: "fallback_required",
        apiCategory: null,
        apiSubcategory: null,
        fallbackStrategy: "future_custom_source_required",
        fallbackRequired: true,
      }),
      createCard({
        id: "thinking-focus",
        title: "ركز شوي",
        description: "أسئلة ملاحظة دقيقة تحتاج تركيزًا على تفاصيل صغيرة.",
        imageKey: "thinking-focus",
        iconKey: "focus",
        infoTitle: "ركز شوي",
        infoBody: "فرع مخصص للتفاصيل الدقيقة مثل اختلافات بسيطة أو ترتيب عناصر أو ملاحظات مخفية.",
        apiSource: "fallback_required",
        apiCategory: null,
        apiSubcategory: null,
        fallbackStrategy: "future_custom_source_required",
        fallbackRequired: true,
      }),
      createCard({
        id: "thinking-riddles",
        title: "ألغاز",
        description: "ألغاز منطقية وكلاسيكية مع إجابات مباشرة.",
        imageKey: "thinking-riddles",
        iconKey: "riddle",
        infoTitle: "ألغاز",
        infoBody: "ألغاز قصيرة تعتمد على التفكير المنطقي أو الحل اللفظي السريع.",
        apiSource: "fallback_required",
        apiCategory: null,
        apiSubcategory: null,
        fallbackStrategy: "curated_local_bank",
        fallbackRequired: true,
      }),
      createCard({
        id: "thinking-riddle-and-proverb",
        title: "لغز ومثل",
        description: "أسئلة تمزج بين اللغز والمثل الشعبي.",
        imageKey: "thinking-riddle-and-proverb",
        iconKey: "lightbulb",
        infoTitle: "لغز ومثل",
        infoBody: "الجواب قد يكون مثلًا شائعًا أو عبارة مرتبطة بحل لغز وصفي.",
        apiSource: "fallback_required",
        apiCategory: "culture",
        apiSubcategory: "riddle_and_proverb",
        fallbackStrategy: "curated_local_bank",
        fallbackRequired: true,
      }),
      createCard({
        id: "thinking-proverbs-and-riddles",
        title: "أمثال و ألغاز",
        description: "أمثال شعبية وألغاز ذهنية ضمن نفس الفرع.",
        imageKey: "thinking-proverbs-and-riddles",
        iconKey: "quote-puzzle",
        infoTitle: "أمثال و ألغاز",
        infoBody: "مناسب لجولات تعتمد على الثقافة العامة والربط بين الأمثال والألغاز.",
        apiSource: "fallback_required",
        apiCategory: "culture",
        apiSubcategory: "proverbs_and_riddles",
        fallbackStrategy: "curated_local_bank",
        fallbackRequired: true,
      }),
      createCard({
        id: "thinking-drawing",
        title: "رسم",
        description: "التعرّف على الشيء من رسمة أو تخطيط مبسّط.",
        imageKey: "thinking-drawing",
        iconKey: "draw",
        infoTitle: "رسم",
        infoBody: "أسئلة بصرية مبنية على رسومات مبسطة أو doodles، وليست مناسبة لمصدر trivia API عام.",
        apiSource: "fallback_required",
        apiCategory: null,
        apiSubcategory: null,
        fallbackStrategy: "future_custom_source_required",
        fallbackRequired: true,
      }),
      createCard({
        id: "thinking-color-image",
        title: "لون الصورة",
        description: "تمييز الشيء أو الدولة أو العلامة عبر ألوان الصورة.",
        imageKey: "thinking-color-image",
        iconKey: "palette",
        infoTitle: "لون الصورة",
        infoBody: "يعتمد على استخدام اللون كدليل بصري، مثل مطابقة العلم أو الشعار أو العنصر الصحيح.",
        apiSource: "fallback_required",
        apiCategory: null,
        apiSubcategory: null,
        fallbackStrategy: "future_custom_source_required",
        fallbackRequired: true,
      }),
      createCard({
        id: "thinking-reversed-words",
        title: "كلمات معكوسة",
        description: "كلمات أو أسماء معروضة بشكل معكوس أو مقلوب.",
        imageKey: "thinking-reversed-words",
        iconKey: "reverse-word",
        infoTitle: "كلمات معكوسة",
        infoBody: "فرع لفظي بصري يحتاج معالجة نصية خاصة، ولا يوجد له مصدر API جاهز ومنظف.",
        apiSource: "fallback_required",
        apiCategory: "wordplay",
        apiSubcategory: "reversed_words",
        fallbackStrategy: "curated_local_bank",
        fallbackRequired: true,
      }),
    ],
  }),
  createSection({
    id: "no-word",
    title: "ولاكلمة",
    description: "فروع وصف وتخمين بدون ذكر الكلمة الأساسية مباشرة.",
    cardTitleColor: "orange",
    layout: "tile-grid",
    subcategories: [
      createCard({
        id: "no-word-foreign",
        title: "ولا كلمة من أجنبي",
        description: "وصف أفلام أو شخصيات أو أعمال أجنبية بدون الاسم.",
        imageKey: "no-word-foreign",
        iconKey: "foreign-guess",
        infoTitle: "ولا كلمة من أجنبي",
        infoBody: "اللعب هنا يعتمد على وصف عمل أجنبي أو شخصية أجنبية من غير التلفظ بالاسم.",
        apiSource: "fallback_required",
        apiCategory: "entertainment",
        apiSubcategory: "foreign_media_guess",
        fallbackStrategy: "future_custom_source_required",
        fallbackRequired: true,
      }),
      createCard({
        id: "no-word-football",
        title: "ولا كلمة كروية",
        description: "وصف لاعب أو نادٍ أو بطولة كروية بدون الاسم.",
        imageKey: "no-word-football",
        iconKey: "football-guess",
        infoTitle: "ولا كلمة كروية",
        infoBody: "فرع مناسب لجولات الوصف السريع لمحبي الكرة، لكنه يحتاج بنكًا مخصصًا وليس API جاهزًا.",
        apiSource: "fallback_required",
        apiCategory: "sports",
        apiSubcategory: "football_guess",
        fallbackStrategy: "curated_local_bank",
        fallbackRequired: true,
      }),
      createCard({
        id: "no-word-proverbs",
        title: "ولا كلمة أمثال",
        description: "وصف أمثال شعبية بدون قول كلماتها الأصلية.",
        imageKey: "no-word-proverbs",
        iconKey: "proverb-guess",
        infoTitle: "ولا كلمة أمثال",
        infoBody: "يحتاج هذا الفرع محتوى عربيًا مخصصًا لأن الأمثال الشعبية لا تغطيها trivia APIs العامة بشكل جيد.",
        apiSource: "fallback_required",
        apiCategory: "culture",
        apiSubcategory: "proverbs",
        fallbackStrategy: "curated_local_bank",
        fallbackRequired: true,
      }),
      createCard({
        id: "no-word-general",
        title: "ولا كلمة عامة",
        description: "وصف أشياء وأماكن ومفاهيم عامة بالعربية دون ذكر الاسم.",
        imageKey: "no-word-general",
        iconKey: "general-guess",
        infoTitle: "ولا كلمة عامة",
        infoBody: "هذا الفرع يعطي كلمات عربية عامة داخل جلسة خاصة برمز QR ليظهر السر على جهاز الممثل فقط.",
        apiSource: "fallback_required",
        apiCategory: "general",
        apiSubcategory: "guess_without_word",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
      createCard({
        id: "no-word-default",
        title: "ولا كلمة",
        description: "باركود يعرض اسم فيلم أو مسلسل أو أغنية أو مسرحية للممثل فقط.",
        imageKey: "no-word-default",
        iconKey: "no-word",
        infoTitle: "ولا كلمة",
        infoBody: "هذا الفرع مخصص للأعمال الفنية بالعربية: فيلم أو مسلسل أو أغنية أو مسرحية، ويعمل كجلسة منفصلة مع رابط خاص للممثل.",
        apiSource: "fallback_required",
        apiCategory: "general",
        apiSubcategory: "open_guess",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
      createCard({
        id: "no-word-islamic",
        title: "ولا كلمة إسلامي",
        description: "وصف أسماء ومفاهيم إسلامية بدون التلفظ بها.",
        imageKey: "islamic-general",
        iconKey: "islamic-general",
        infoTitle: "ولا كلمة إسلامي",
        infoBody: "هذا الفرع يعمل من IslamicQuizAPI كجلسة سرية منفصلة للممثل، ويُولّد السر من سجل حي عربي واحد.",
        apiSource: "islamic_quiz_api",
        apiCategory: "islamic",
        apiSubcategory: "guess_without_word_islamic",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
      createCard({
        id: "no-word-anime",
        title: "ولا كلمة أنمي",
        description: "وصف شخصيات أو أعمال أنمي بدون الاسم.",
        imageKey: "no-word-anime",
        iconKey: "anime-guess",
        infoTitle: "ولا كلمة أنمي",
        infoBody: "يمكن الاستفادة من مصادر anime للبيانات لاحقًا، لكن صياغة اللعبة نفسها تحتاج fallback مخصص.",
        apiSource: "fallback_required",
        apiCategory: "anime",
        apiSubcategory: "anime_guess",
        fallbackStrategy: "future_custom_source_required",
        fallbackRequired: true,
      }),
      createCard({
        id: "no-word-wrestling",
        title: "ولا كلمة مصارعة",
        description: "وصف مصارعين أو عروض مصارعة بدون الاسم.",
        imageKey: "no-word-wrestling",
        iconKey: "wrestling-guess",
        infoTitle: "ولا كلمة مصارعة",
        infoBody: "فرع متخصص جدًا ولا يملك مصدر trivia عام جيد بالعربية، لذلك يحتاج fallback.",
        apiSource: "fallback_required",
        apiCategory: "sports_entertainment",
        apiSubcategory: "wrestling_guess",
        fallbackStrategy: "curated_local_bank",
        fallbackRequired: true,
      }),
    ],
  }),
  createSection({
    id: "letters",
    title: "حروف",
    description: "فروع لفظية مبنية على الحروف والتصنيف وسرعة الاستحضار.",
    cardTitleColor: "orange",
    layout: "tile-grid",
    subcategories: [
      createCard({
        id: "letters-football",
        title: "حروف كروية",
        description: "أندية ولاعبون وملاعب بحسب الحرف.",
        imageKey: "letters-football",
        iconKey: "football-letter",
        infoTitle: "حروف كروية",
        infoBody: "هذا الفرع مولد الآن من API داخلي بالعربية يعتمد على الحرف الأول والوصف داخل مجال كرة القدم.",
        apiSource: "internal_letters_api",
        apiCategory: "sports",
        apiSubcategory: "football_letters",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
      createCard({
        id: "letters-singing",
        title: "حروف غنائي",
        description: "مطربون وأغانٍ وآلات بحسب الحرف.",
        imageKey: "letters-singing",
        iconKey: "music-letter",
        infoTitle: "حروف غنائي",
        infoBody: "هذا الفرع مولد الآن من API داخلي بالعربية يعتمد على الحرف الأول ووصف متعلق بالموسيقى والغناء.",
        apiSource: "internal_letters_api",
        apiCategory: "music",
        apiSubcategory: "music_letters",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
      createCard({
        id: "letters-islamic",
        title: "حروف إسلامي",
        description: "مصطلحات أو سور أو أسماء إسلامية بحسب الحرف.",
        imageKey: "letters-islamic",
        iconKey: "islamic-letter",
        infoTitle: "حروف إسلامي",
        infoBody: "هذا الفرع مولد الآن من API داخلي بالعربية ويعطي مصطلحات إسلامية مبنية على الحرف الأول والوصف.",
        apiSource: "internal_letters_api",
        apiCategory: "islamic",
        apiSubcategory: "islamic_letters",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
      createCard({
        id: "letters-general",
        title: "حروف",
        description: "نسخة عامة من لعبة الحروف.",
        imageKey: "letters-general",
        iconKey: "letters",
        infoTitle: "حروف",
        infoBody: "نسخة عامة مولدة من API داخلي بالعربية وتعتمد على الحرف الأول ووصف مباشر للكلمة المطلوبة.",
        apiSource: "internal_letters_api",
        apiCategory: "general",
        apiSubcategory: "letters",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
      createCard({
        id: "letters-moving",
        title: "حروف متحركة",
        description: "ألغاز نصية مرنة تعتمد على حركة الحروف أو تبديلها.",
        imageKey: "letters-moving",
        iconKey: "moving-letters",
        infoTitle: "حروف متحركة",
        infoBody: "هذا الفرع يعمل الآن عبر API داخلي بالعربية ويركز على أشياء أو وسائل تتحرك مع دلالة الحرف الأول.",
        apiSource: "internal_letters_api",
        apiCategory: "wordplay",
        apiSubcategory: "moving_letters",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
      createCard({
        id: "letters-anime",
        title: "حروف أنمي",
        description: "شخصيات وأعمال أنمي بحسب الحرف.",
        imageKey: "letters-anime",
        iconKey: "anime-letter",
        infoTitle: "حروف أنمي",
        infoBody: "هذا الفرع مولد الآن من API داخلي بالعربية ويعتمد على الحرف الأول ووصف شخصية أو عمل أنمي معروف.",
        apiSource: "internal_letters_api",
        apiCategory: "anime",
        apiSubcategory: "anime_letters",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
    ],
  }),
  createSection({
    id: "countries",
    title: "دول",
    description: "دول وعواصم وأعلام وعملات ولغات وجغرافيا عالمية.",
    cardTitleColor: "orange",
    layout: "tile-grid",
    subcategories: [
      createCard({
        id: "countries-currencies",
        title: "عملات",
        description: "أسئلة حول العملات الرسمية للدول.",
        imageKey: "countries-currencies",
        iconKey: "currency",
        infoTitle: "عملات",
        infoBody: "أفضل مصدر هنا هو بيانات الدول والعملات وليس trivia API عام.",
        apiSource: "rest_countries",
        apiCategory: "country_data",
        apiSubcategory: "currencies",
        fallbackStrategy: "hybrid_api_plus_local_templates",
        fallbackRequired: false,
      }),
      createCard({
        id: "countries-aviation",
        title: "عالم الطيران",
        description: "مطارات وشركات طيران ومفاهيم سفر جوي.",
        imageKey: "countries-aviation",
        iconKey: "aviation",
        infoTitle: "عالم الطيران",
        infoBody: "هذا الفرع يعمل حاليًا بقوالب أسئلة سفر جوي مبنية على REST Countries مثل العاصمة والإقليم والمناطق الزمنية، وليس بقاعدة طيران متخصصة كاملة.",
        apiSource: "hybrid_countries",
        apiCategory: "travel",
        apiSubcategory: "aviation",
        fallbackStrategy: "hybrid_api_plus_local_templates",
        fallbackRequired: false,
      }),
      createCard({
        id: "countries-travel",
        title: "سياحة وسفر",
        description: "وجهات ومعالم وتجارب سياحية حول العالم.",
        imageKey: "countries-travel",
        iconKey: "travel",
        infoTitle: "سياحة وسفر",
        infoBody: "يمكن دعمه جزئيًا من بيانات دول ومعالم، لكن عادة يحتاج fallback وصياغة محلية.",
        apiSource: "hybrid_countries",
        apiCategory: "travel",
        apiSubcategory: "tourism",
        fallbackStrategy: "hybrid_api_plus_local_templates",
        fallbackRequired: false,
      }),
      createCard({
        id: "countries-country-capitals",
        title: "دول و عواصم",
        description: "ربط الدولة بعاصمتها والعكس.",
        imageKey: "countries-country-capitals",
        iconKey: "country-capital",
        infoTitle: "دول و عواصم",
        infoBody: "واحد من أوضح الفروع لربطه مباشرة ببيانات REST Countries.",
        apiSource: "rest_countries",
        apiCategory: "country_data",
        apiSubcategory: "capital_pairs",
        fallbackStrategy: "hybrid_api_plus_local_templates",
        fallbackRequired: false,
      }),
      createCard({
        id: "countries-geography",
        title: "جغرافيا",
        description: "مناطق وحدود ومواقع وقارات.",
        imageKey: "countries-geography",
        iconKey: "geography",
        infoTitle: "جغرافيا",
        infoBody: "يمكن دعم جزء منه من بيانات الدول، لكن الأسئلة الأعمق تحتاج fallback عام أو محلي.",
        apiSource: "hybrid_countries",
        apiCategory: "geography",
        apiSubcategory: "country_geography",
        fallbackStrategy: "hybrid_api_plus_local_templates",
        fallbackRequired: false,
      }),
      createCard({
        id: "countries-old-flags",
        title: "أعلام قديمة",
        description: "أعلام تاريخية أو أعلام قبل التغيير.",
        imageKey: "countries-old-flags",
        iconKey: "old-flag",
        infoTitle: "أعلام قديمة",
        infoBody: "REST Countries لا يغطي الأعلام القديمة تاريخيًا بشكل مباشر، لذلك هذا فرع fallback واضح.",
        apiSource: "fallback_required",
        apiCategory: "history",
        apiSubcategory: "historical_flags",
        fallbackStrategy: "curated_local_bank",
        fallbackRequired: true,
      }),
      createCard({
        id: "countries-flags",
        title: "أعلام",
        description: "تعرف على الدولة من علمها.",
        imageKey: "countries-flags",
        iconKey: "flag",
        infoTitle: "أعلام",
        infoBody: "أفضل ربط مباشر هنا مع REST Countries لأن العلم متوفر كبيان رسمي.",
        apiSource: "rest_countries",
        apiCategory: "country_data",
        apiSubcategory: "flags",
        fallbackStrategy: "hybrid_api_plus_local_templates",
        fallbackRequired: false,
      }),
      createCard({
        id: "countries-presidents",
        title: "رؤساء الدول",
        description: "قادة ورؤساء وشخصيات مرتبطة بدولهم.",
        imageKey: "countries-presidents",
        iconKey: "leaders",
        infoTitle: "رؤساء الدول",
        infoBody: "هناك اتجاه مستقبلي ممكن عبر Wikidata/SPARQL، لكن هذا الفرع غير موصول الآن داخل اللعبة لذلك هو تحت الإنشاء.",
        apiSource: "fallback_required",
        apiCategory: "politics",
        apiSubcategory: "country_leaders",
        fallbackStrategy: "curated_local_bank",
        fallbackRequired: true,
      }),
      createCard({
        id: "countries-what-country",
        title: "ما هي الدولة",
        description: "اكتشاف الدولة من أكثر من دليل.",
        imageKey: "countries-what-country",
        iconKey: "identify-country",
        infoTitle: "ما هي الدولة",
        infoBody: "مناسب جدًا للنمط الهجين: بيانات دول + قالب سؤال يجمع العاصمة واللغة والعلم.",
        apiSource: "hybrid_countries",
        apiCategory: "country_data",
        apiSubcategory: "identify_country",
        fallbackStrategy: "hybrid_api_plus_local_templates",
        fallbackRequired: false,
      }),
      createCard({
        id: "countries-uk-batch",
        title: "دفعة بريطانيا",
        description: "أسئلة مرتبطة ببريطانيا ولندن ورموزها.",
        imageKey: "countries-uk-batch",
        iconKey: "uk",
        flagCode: "GB",
        infoTitle: "دفعة بريطانيا",
        infoBody: "فرع خاص ومخصص جدًا؛ يمكن الاستفادة من بيانات بريطانيا العامة لكن المحتوى نفسه يحتاج fallback محلي.",
        apiSource: "fallback_required",
        apiCategory: "country_data",
        apiSubcategory: "uk_specific",
        fallbackStrategy: "hybrid_api_plus_local_templates",
        fallbackRequired: true,
      }),
      createCard({
        id: "countries-languages",
        title: "لغات ولهجات",
        description: "لغات الدول واللهجات المرتبطة بالمناطق.",
        imageKey: "countries-languages",
        iconKey: "languages",
        infoTitle: "لغات ولهجات",
        infoBody: "لغات الدول يمكن أخذها من REST Countries، أما اللهجات فتحتاج صياغة إضافية أو fallback.",
        apiSource: "hybrid_countries",
        apiCategory: "country_data",
        apiSubcategory: "languages",
        fallbackStrategy: "hybrid_api_plus_local_templates",
        fallbackRequired: false,
      }),
      createCard({
        id: "countries-anthem",
        title: "النشيد الوطني",
        description: "أناشيد وطنية وهوية الدول الصوتية أو النصية.",
        imageKey: "countries-anthem",
        iconKey: "anthem",
        infoTitle: "النشيد الوطني",
        infoBody: "لم نجد مسار API trivia-ready نظيفًا وعمليًا لهذا الفرع داخل التطبيق الحالي، لذلك يبقى تحت الإنشاء.",
        apiSource: "fallback_required",
        apiCategory: "country_identity",
        apiSubcategory: "anthems",
        fallbackStrategy: "curated_local_bank",
        fallbackRequired: true,
      }),
      createCard({
        id: "countries-world-war",
        title: "الحرب العالمية",
        description: "أحداث ودول ومحطات من الحربين العالميتين.",
        imageKey: "countries-world-war",
        iconKey: "world-war",
        infoTitle: "الحرب العالمية",
        infoBody: "يمكن بناؤه لاحقًا من مصادر تاريخ عامة، لكن لا يوجد ربط API جاهز وموثوق له في هذا الإصدار، لذلك هو تحت الإنشاء.",
        apiSource: "fallback_required",
        apiCategory: "history",
        apiSubcategory: "world_wars",
        fallbackStrategy: "future_custom_source_required",
        fallbackRequired: true,
      }),
      createCard({
        id: "countries-maps",
        title: "خرائط",
        description: "التعرف على الدول أو المواقع عبر الخريطة.",
        imageKey: "countries-maps",
        iconKey: "maps",
        infoTitle: "خرائط",
        infoBody: "هذا فرع بصري أكثر من كونه trivia text، لذا يحتاج مصدر صور وخرائط أو fallback مخصص.",
        apiSource: "fallback_required",
        apiCategory: "maps",
        apiSubcategory: "map_guess",
        fallbackStrategy: "future_custom_source_required",
        fallbackRequired: true,
      }),
      createCard({
        id: "countries-capitals",
        title: "عواصم",
        description: "عواصم الدول المعروفة والصعبة.",
        imageKey: "countries-capitals",
        iconKey: "capitals",
        infoTitle: "عواصم",
        infoBody: "أفضل خيار هنا REST Countries لأنه يوفر العاصمة بشكل مباشر وثابت نسبيًا.",
        apiSource: "rest_countries",
        apiCategory: "country_data",
        apiSubcategory: "capitals",
        fallbackStrategy: "hybrid_api_plus_local_templates",
        fallbackRequired: false,
      }),
    ],
  }),
  createSection({
    id: "islamic",
    title: "إسلامي",
    description: "فروع إسلامية حية من IslamicQuizAPI مع بنية فئات وموضوعات عربية.",
    cardTitleColor: "orange",
    layout: "tile-grid",
    subcategories: [
      createCard({
        id: "islamic-tafseer",
        title: "التفسير",
        description: "أسئلة في تفسير الآيات والمعاني والسياقات القرآنية.",
        imageKey: "islamic-general",
        iconKey: "islamic-general",
        infoTitle: "التفسير",
        infoBody: "هذا الفرع يأتي مباشرة من IslamicQuizAPI عبر فئة عربية حية مع موضوعات فرعية يتم جلبها وقت التحضير.",
        apiSource: "islamic_quiz_api",
        apiCategory: "التفسير",
        apiSubcategory: "التفسير",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
      createCard({
        id: "islamic-aqeedah",
        title: "العقيدة",
        description: "أسئلة في أصول الاعتقاد والمفاهيم الإيمانية الأساسية.",
        imageKey: "islamic-quran-meanings",
        iconKey: "quran-meanings",
        infoTitle: "العقيدة",
        infoBody: "هذا الفرع يستخدم IslamicQuizAPI مباشرة ويعتمد على سجلات عربية حية يتم التحقق منها قبل عرضها في اللوحة.",
        apiSource: "islamic_quiz_api",
        apiCategory: "العقيدة",
        apiSubcategory: "العقيدة",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
      createCard({
        id: "islamic-hadith",
        title: "الحديث",
        description: "أسئلة في الأحاديث ومتونها ومعانيها ومصادرها.",
        imageKey: "islamic-prophets-stories",
        iconKey: "prophets",
        infoTitle: "الحديث",
        infoBody: "هذا الفرع يأتي من IslamicQuizAPI بفروع موضوعية عربية، ثم يحوله backend إلى أسئلة reveal مع إجابات مرتبطة بنفس السجل.",
        apiSource: "islamic_quiz_api",
        apiCategory: "الحديث",
        apiSubcategory: "الحديث",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
      createCard({
        id: "islamic-fiqh",
        title: "الفقه",
        description: "أسئلة في الأحكام والعبادات والمعاملات المشهورة.",
        imageKey: "islamic-quran",
        iconKey: "quran",
        infoTitle: "الفقه",
        infoBody: "هذا الفرع يستخدم IslamicQuizAPI كمصدر حي للفئة والموضوع، بدون أي fallback محلي أثناء اللعب.",
        apiSource: "islamic_quiz_api",
        apiCategory: "الفقه",
        apiSubcategory: "الفقه",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
      createCard({
        id: "islamic-history",
        title: "التاريخ",
        description: "أسئلة في التاريخ الإسلامي والأحداث والشخصيات المرتبطة به.",
        imageKey: "general-history",
        iconKey: "history",
        infoTitle: "التاريخ",
        infoBody: "هذا الفرع يأتي من IslamicQuizAPI ضمن الفئة الإسلامية التاريخية، مع تطبيع عربي كامل قبل الإرسال للواجهة.",
        apiSource: "islamic_quiz_api",
        apiCategory: "التاريخ",
        apiSubcategory: "التاريخ",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
      createCard({
        id: "islamic-arabic-language",
        title: "اللغة العربية",
        description: "أسئلة لغوية عربية ضمن السياق الإسلامي ومجالاته المعرفية.",
        imageKey: "general-language-literature",
        iconKey: "language-literature",
        infoTitle: "اللغة العربية",
        infoBody: "هذا الفرع يعتمد على IslamicQuizAPI مباشرة ويستفيد من البنية العربية الأصلية للسؤال والجواب دون ترجمة وسيطة.",
        apiSource: "islamic_quiz_api",
        apiCategory: "اللغة العربية",
        apiSubcategory: "اللغة العربية",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
    ],
  }),
  createSection({
    id: "general",
    title: "عام",
    description: "معرفة عامة، تقنية، تاريخ، أدب، شعارات، منتجات، وحيوان.",
    cardTitleColor: "orange",
    layout: "tile-grid",
    subcategories: [
      createCard({
        id: "general-technology",
        title: "تكنولوجيا",
        description: "تقنية وشركات وأجهزة ومنصات رقمية.",
        imageKey: "general-technology",
        iconKey: "technology",
        infoTitle: "تكنولوجيا",
        infoBody: "هذا الفرع يجلب أسئلة حاسوب وتقنية من Open Trivia DB بالإنجليزية، ثم يترجم السؤال والجواب عبر LibreTranslate إلى عربية reveal فقط دون بنك محلي.",
        apiSource: "open_trivia_db",
        apiCategory: "Science: Computers",
        apiSubcategory: "technology",
        fallbackStrategy: "translate_general_source",
        fallbackRequired: false,
      }),
      createCard({
        id: "general-general-knowledge",
        title: "معلومات عامة",
        description: "أسئلة منوعة في الثقافة العامة.",
        imageKey: "general-general-knowledge",
        iconKey: "general-knowledge",
        infoTitle: "معلومات عامة",
        infoBody: "هذا الفرع يستخدم The Trivia API v2 فقط (علامات geography/history/science/arts_and_literature) بالإنجليزية، ثم LibreTranslate لإنتاج سؤال وجواب عربيين reveal دون بنك محلي.",
        apiSource: "hybrid_general",
        apiCategory: "General Knowledge",
        apiSubcategory: "general_knowledge",
        fallbackStrategy: "translate_general_source",
        fallbackRequired: false,
      }),
      createCard({
        id: "general-history",
        title: "تاريخ",
        description: "أحداث وشخصيات تاريخية.",
        imageKey: "general-history",
        iconKey: "history",
        infoTitle: "تاريخ",
        infoBody: "هذا الفرع يعتمد على Open Trivia DB (فئة التاريخ) مع تصفية صارمة للجودة، ثم LibreTranslate لإخراج reveal عربي دون بنك محلي.",
        apiSource: "open_trivia_db",
        apiCategory: "History",
        apiSubcategory: "history",
        fallbackStrategy: "translate_general_source",
        fallbackRequired: false,
      }),
      createCard({
        id: "general-poetry",
        title: "عالم الشعر",
        description: "شعراء وقصائد وأبيات وأدب شعري.",
        imageKey: "general-poetry",
        iconKey: "poetry",
        infoTitle: "عالم الشعر",
        infoBody: "لا يوجد مصدر trivia عام نظيف لهذا الفرع العربي تحديدًا، لذلك fallback واضح.",
        apiSource: "fallback_required",
        apiCategory: "literature",
        apiSubcategory: "poetry",
        fallbackStrategy: "curated_local_bank",
        fallbackRequired: true,
      }),
      createCard({
        id: "general-language-literature",
        title: "لغة وأدب",
        description: "مفردات وأدباء وأعمال أدبية.",
        imageKey: "general-language-literature",
        iconKey: "language-literature",
        infoTitle: "لغة وأدب",
        infoBody: "هذا الفرع يعمل عبر KalimaLab كمصدر عربي مباشر، ثم يطبّق backend التحقق قبل تجهيز الأسئلة للوحة.",
        apiSource: "kalimalab",
        apiCategory: "Entertainment: Books",
        apiSubcategory: "language_literature",
        fallbackStrategy: "hybrid_api_plus_local_templates",
        fallbackRequired: false,
      }),
      createCard({
        id: "general-refrigerators",
        title: "برادات",
        description: "سلع ومنتجات منزلية وتجارية.",
        imageKey: "general-refrigerators",
        iconKey: "shopping",
        flagCode: "QA",
        infoTitle: "برادات",
        infoBody: "فرع شديد التخصص وغير مناسب لـ public trivia APIs، لذلك fallback فقط.",
        apiSource: "fallback_required",
        apiCategory: "products",
        apiSubcategory: "retail_items",
        fallbackStrategy: "curated_local_bank",
        fallbackRequired: true,
      }),
      createCard({
        id: "general-products",
        title: "منتجات",
        description: "تعرف على المنتج أو الشركة أو الاستخدام.",
        imageKey: "general-products",
        iconKey: "products",
        flagCode: "KW",
        infoTitle: "منتجات",
        infoBody: "المنتجات تحتاج catalog محلي أو fallback منظم، ولا يوجد API trivia نظيف يغطيها كما هي.",
        apiSource: "fallback_required",
        apiCategory: "products",
        apiSubcategory: "consumer_products",
        fallbackStrategy: "curated_local_bank",
        fallbackRequired: true,
      }),
      createCard({
        id: "general-global-logos",
        title: "شعارات عالمية",
        description: "علامات وشعارات دولية معروفة.",
        imageKey: "general-global-logos",
        iconKey: "global-logos",
        infoTitle: "شعارات عالمية",
        infoBody: "هذا الفرع يعمل الآن من API Ninjas Logo API ويعرض الشعار أولًا ثم يكشف الاسم العربي للعلامة بعد reveal.",
        apiSource: "api_ninjas_logo",
        apiCategory: "brands",
        apiSubcategory: "global_logos",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
      createCard({
        id: "general-logos",
        title: "شعارات",
        description: "شعارات عامة أو محلية وإقليمية.",
        imageKey: "general-logos",
        iconKey: "logos",
        flagCode: "KW",
        infoTitle: "شعارات",
        infoBody: "يعتمد هذا الفرع على سجل حي من API Ninjas Logo API: الشعار من نفس السجل والاسم العربي يُكشف بعد reveal فقط.",
        apiSource: "api_ninjas_logo",
        apiCategory: "brands",
        apiSubcategory: "logos",
        fallbackStrategy: "none",
        fallbackRequired: false,
      }),
      createCard({
        id: "general-animals",
        title: "عالم الحيوان",
        description: "حيوانات وحقائق مبسطة ومشهورة.",
        imageKey: "general-animals",
        iconKey: "animals",
        infoTitle: "عالم الحيوان",
        infoBody: "هذا الفرع يستخدم Open Trivia DB (فئة الحيوان) مع ترشيح للأسئلة الأكثر عمقًا، ثم LibreTranslate لصياغة reveal عربية دون بنك محلي.",
        apiSource: "open_trivia_db",
        apiCategory: "Animals",
        apiSubcategory: "animals",
        fallbackStrategy: "translate_general_source",
        fallbackRequired: false,
      }),
      createCard({
        id: "general-celebrity-voice",
        title: "صوت المشهور",
        description: "تخمين المشهور من وصف أو سياق صوتي.",
        imageKey: "general-celebrity-voice",
        iconKey: "celebrity-voice",
        infoTitle: "صوت المشهور",
        infoBody: "هذا فرع صوتي أو وصفي ويحتاج وسائط أو fallback مخصص؛ trivia APIs العامة لا تغطيه كما هو.",
        apiSource: "fallback_required",
        apiCategory: "celebrities",
        apiSubcategory: "voice_guess",
        fallbackStrategy: "future_custom_source_required",
        fallbackRequired: true,
      }),
    ],
  }),
];

export const categoryCatalogById = Object.fromEntries(
  categoryCatalog.map((section) => [section.id, section])
) as Record<string, QuizCategorySection>;

export const subcategoryCatalogById = Object.fromEntries(
  categoryCatalog.flatMap((section) =>
    section.subcategories.map((subcategory) => [subcategory.id, subcategory])
  )
) as Record<string, QuizSubcategoryCard>;
// Purpose: define the category cards rendered by the live selection UI.
