// Purpose: keep the legacy subcategory config aligned with the live backend taxonomy.
export const SUBCATEGORY_CONFIG = {
  general: [
    {
      id: "technology",
      categoryId: "general",
      name: "تكنولوجيا",
      description: "أجهزة ومنصات وشركات رقمية معروفة.",
      icon: "💻",
      flag: null,
      provider: "general_api",
      info: "Open Trivia DB بالإنجليزية ثم LibreTranslate لعربية reveal دون بنك محلي.",
    },
    {
      id: "general_info",
      categoryId: "general",
      name: "معلومات عامة",
      description: "أسئلة منوعة في الثقافة العامة.",
      icon: "📋",
      flag: null,
      provider: "general_api",
      info: "The Trivia API v2 بالإنجليزية ثم LibreTranslate لعربية reveal دون بنك محلي.",
    },
    {
      id: "history",
      categoryId: "general",
      name: "تاريخ",
      description: "أحداث وشخصيات ومحطات تاريخية.",
      icon: "🏛️",
      flag: null,
      provider: "general_api",
      info: "Open Trivia DB (تاريخ) + LibreTranslate مع تصفية جودة لعربية reveal.",
    },
    {
      id: "language_literature",
      categoryId: "general",
      name: "لغة وأدب",
      description: "مفردات وأدباء وأعمال أدبية.",
      icon: "📚",
      flag: null,
      provider: "general_api",
      info: "أسئلة عربية وأدبية تصلح لجولات ثقافية كلاسيكية.",
    },
    {
      id: "logos_brands",
      categoryId: "general",
      name: "شعارات وعلامات تجارية",
      description: "شعارات شركات وعلامات معروفة في وضع كشف بصري.",
      icon: "🏷️",
      flag: null,
      provider: "general_api",
      info: "API Ninjas Logo API باستعلامات أسماء/رموز مُجهّزة، ثم LibreTranslate للاسم العربي وreveal_visual.",
    },
  ],
  islamic: [
    {
      id: "tafseer",
      categoryId: "islamic",
      name: "التفسير",
      description: "تفسير الآيات ومعانيها وسياقاتها.",
      icon: "📖",
      flag: null,
      provider: "islamic_quiz_api",
      info: "أسئلة عربية حية من IslamicQuizAPI مع موضوعات تفسيرية متعددة.",
    },
    {
      id: "aqeedah",
      categoryId: "islamic",
      name: "العقيدة",
      description: "أصول الاعتقاد والمفاهيم الإيمانية.",
      icon: "🕋",
      flag: null,
      provider: "islamic_quiz_api",
      info: "أسئلة عربية حية في العقيدة من IslamicQuizAPI.",
    },
    {
      id: "hadith",
      categoryId: "islamic",
      name: "الحديث",
      description: "أحاديث ومتون ومعانٍ ومصادر.",
      icon: "🌙",
      flag: null,
      provider: "islamic_quiz_api",
      info: "أسئلة عربية حية في الحديث من IslamicQuizAPI.",
    },
    {
      id: "fiqh",
      categoryId: "islamic",
      name: "الفقه",
      description: "أحكام وعبادات ومعاملات معروفة.",
      icon: "🪶",
      flag: null,
      provider: "islamic_quiz_api",
      info: "أسئلة عربية حية في الفقه من IslamicQuizAPI.",
    },
    {
      id: "history",
      categoryId: "islamic",
      name: "التاريخ",
      description: "أحداث وشخصيات ومعالم من التاريخ الإسلامي.",
      icon: "🏛️",
      flag: null,
      provider: "islamic_quiz_api",
      info: "أسئلة عربية حية في التاريخ الإسلامي من IslamicQuizAPI.",
    },
    {
      id: "arabic_language",
      categoryId: "islamic",
      name: "اللغة العربية",
      description: "لغة عربية ومصطلحات وسياقات معرفية.",
      icon: "📚",
      flag: null,
      provider: "islamic_quiz_api",
      info: "أسئلة عربية حية في اللغة العربية من IslamicQuizAPI.",
    },
  ],
  countries: [
    {
      id: "flags",
      categoryId: "countries",
      name: "أعلام",
      description: "تعرف على الدولة من علمها.",
      icon: "🚩",
      flag: "🌐",
      provider: "countries_api",
      info: "أسئلة تعتمد على الأعلام والتمييز بين الدول.",
    },
    {
      id: "capitals",
      categoryId: "countries",
      name: "عواصم",
      description: "أسئلة مباشرة حول عواصم العالم.",
      icon: "🏙️",
      flag: null,
      provider: "countries_api",
      info: "مناسب لجولات الدول والعواصم السريعة والواضحة.",
    },
    {
      id: "currencies",
      categoryId: "countries",
      name: "عملات",
      description: "تعرف على العملة الرسمية للدول.",
      icon: "💰",
      flag: null,
      provider: "countries_api",
      info: "يركز على العملات الرسمية ورموزها المعروفة.",
    },
    {
      id: "countries_capitals",
      categoryId: "countries",
      name: "دول و عواصم",
      description: "أسئلة معكوسة بين الدولة والعاصمة.",
      icon: "📍",
      flag: null,
      provider: "countries_api",
      info: "يجمع بين أسئلة ما الدولة وما العاصمة في نفس الفرع.",
    },
  ],
  letters: [
    {
      id: "letters_general",
      categoryId: "letters",
      name: "حروف",
      description: "كلمات وأسماء بحسب الحرف.",
      icon: "🔠",
      flag: null,
      provider: "wordplay_api",
      info: "لعبة مفردات تعتمد على حرف البداية أو النهاية.",
    },
    {
      id: "sports_letters",
      categoryId: "letters",
      name: "حروف كروية",
      description: "أسماء كروية بحسب الحرف.",
      icon: "⚽",
      flag: null,
      provider: "wordplay_api",
      info: "مناسب للأندية واللاعبين والملاعب بحسب الحرف.",
    },
  ],
  "no-word": [
    {
      id: "no_word_general",
      categoryId: "no-word",
      name: "ولا كلمة عامة",
      description: "صف الشيء بدون قول اسمه.",
      icon: "🎭",
      flag: null,
      provider: "wordplay_api",
      info: "لعبة وصف وتخمين بدون التلفظ بالكلمة المطلوبة.",
    },
    {
      id: "no_word_sports",
      categoryId: "no-word",
      name: "ولا كلمة كروية",
      description: "وصف شخصيات وأندية كروية بدون الاسم.",
      icon: "🥅",
      flag: null,
      provider: "wordplay_api",
      info: "فرع مناسب للرياضة والوصف السريع في التحديات الجماعية.",
    },
  ],
};

export function getSubcategoriesByCategory(categoryId) {
  return SUBCATEGORY_CONFIG[categoryId] ?? [];
}

export function getSubcategoryById(categoryId, subcategoryId) {
  return getSubcategoriesByCategory(categoryId).find((item) => item.id === subcategoryId) ?? null;
}
