"""Purpose: explicit name/ticker seeds for API Ninjas Logo queries (live HTTP only; not an offline question bank)."""

# Each entry is either a company keyword or a ticker symbol. API Ninjas requires
# one of name= or ticker= per request and returns at most 10 rows per hit.
BRAND_LOGO_QUERY_SEEDS: list[tuple[str, str]] = [
    ("name", "Nike"),
    ("name", "Apple"),
    ("name", "Google"),
    ("name", "Microsoft"),
    ("name", "Amazon"),
    ("name", "Samsung"),
    ("name", "Toyota"),
    ("name", "Volkswagen"),
    ("name", "BMW"),
    ("name", "Mercedes-Benz"),
    ("name", "Tesla"),
    ("name", "Intel"),
    ("name", "AMD"),
    ("name", "Oracle"),
    ("name", "IBM"),
    ("name", "Cisco"),
    ("name", "Adobe"),
    ("name", "Netflix"),
    ("name", "Spotify"),
    ("name", "Sony"),
    ("name", "LG"),
    ("name", "Panasonic"),
    ("name", "Canon"),
    ("name", "Nikon"),
    ("name", "Visa"),
    ("name", "Mastercard"),
    ("name", "PayPal"),
    ("name", "eBay"),
    ("name", "Coca-Cola"),
    ("name", "Pepsi"),
    ("name", "McDonald's"),
    ("name", "Starbucks"),
    ("name", "IKEA"),
    ("name", "Zara"),
    ("name", "H&M"),
    ("name", "Shell"),
    ("name", "BP"),
    ("name", "ExxonMobil"),
    ("name", "Chevron"),
    ("name", "Uber"),
    ("name", "Airbnb"),
    ("name", "Meta"),
    ("name", "Facebook"),
    ("name", "Instagram"),
    ("name", "Twitter"),
    ("name", "Snapchat"),
    ("name", "TikTok"),
    ("name", "YouTube"),
    ("name", "LinkedIn"),
    ("name", "Salesforce"),
    ("name", "Shopify"),
    ("name", "Zoom"),
    ("name", "Slack"),
    ("name", "Dropbox"),
    ("name", "HP"),
    ("name", "Dell"),
    ("name", "Lenovo"),
    ("name", "Huawei"),
    ("name", "Xiaomi"),
    ("name", "Nintendo"),
    ("name", "PlayStation"),
    ("name", "Xbox"),
    ("name", "Puma"),
    ("name", "Adidas"),
    ("name", "Nestle"),
    ("name", "Unilever"),
    ("name", "Procter & Gamble"),
    ("name", "Johnson & Johnson"),
    ("name", "Pfizer"),
    ("name", "Moderna"),
    ("name", "JPMorgan"),
    ("name", "Goldman Sachs"),
    ("name", "Morgan Stanley"),
    ("name", "Bank of America"),
    ("name", "Wells Fargo"),
    ("name", "Citigroup"),
    ("name", "HSBC"),
    ("name", "Barclays"),
    ("name", "Deutsche Bank"),
    ("name", "Siemens"),
    ("name", "Boeing"),
    ("name", "Airbus"),
    ("name", "Lockheed Martin"),
    ("name", "Raytheon"),
    ("name", "General Electric"),
    ("name", "3M"),
    ("name", "Caterpillar"),
    ("name", "John Deere"),
    ("name", "FedEx"),
    ("name", "UPS"),
    ("name", "DHL"),
    ("name", "Maersk"),
    ("ticker", "AAPL"),
    ("ticker", "MSFT"),
    ("ticker", "GOOGL"),
    ("ticker", "AMZN"),
    ("ticker", "META"),
    ("ticker", "NVDA"),
    ("ticker", "NFLX"),
    ("ticker", "DIS"),
    ("ticker", "KO"),
    ("ticker", "PEP"),
    ("ticker", "MCD"),
    ("ticker", "SBUX"),
    ("ticker", "V"),
    ("ticker", "MA"),
    ("ticker", "PYPL"),
    ("ticker", "INTC"),
    ("ticker", "QCOM"),
    ("ticker", "ORCL"),
    ("ticker", "IBM"),
    ("ticker", "CSCO"),
    ("ticker", "BA"),
    ("ticker", "LMT"),
]
